"""Explicacoes das questoes do exercicio stairs.

O texto esta codificado (ROT13) para nao entregar respostas a
quem so passa o olho. Para ler uma explicacao, descomente a
chamada explicar('nome') correspondente no exercicio e rode.
"""

EXPLICACOES = {
    'maneiras_n3': '\nznarvenf_a3 - a=3, cnffbf=[1, 2]\n\nRahzrer qr sbezn betnavmnqn, ntehcnaqb cryn dhnagvqnqr qr cnffbf\nqr 2:\n\n  - arauhz cnffb qr 2:  1 1 1\n  - hz cnffb qr 2 (r hz cnffb qr 1): b 2 cbqr ive nagrf bh qrcbvf:\n      1 2   r   2 1\n  - qbvf cnffbf qr 2 fbznevnz 4 > 3: vzcbffviry.\n\nGbgny: 3 znarvenf.\n\nReeb pbzhz: pbagne "1 2" r "2 1" pbzb hzn znarven fb. Arfgr ceboyrzn\nn BEQRZ vzcbegn - fnb pnzvaubf qvsreragrf rfpnqn npvzn.\n',
    'maneiras_n5': '\nznarvenf_a5 - a=5, cnffbf=[1, 2]\n\nNtehcr cryn dhnagvqnqr qr cnffbf qr 2:\n\n  - arauhz 2:  1 1 1 1 1                            -> 1 znarven\n  - hz 2: fboenz gerf 1f (dhngeb cnffbf ab gbgny);\n    b 2 cbqr bphcne dhnydhre hzn qnf 4 cbfvpbrf     -> 4 znarvenf\n    Bh frwn: 2 1 1 1\n             1 2 1 1\n             1 1 2 1\n             1 1 1 2\n  - qbvf 2f: fboen hz 1 (gerf cnffbf ab gbgny);\n    b 1 cbqr bphcne dhnydhre hzn qnf 3 cbfvpbrf     -> 3 znarvenf\n    Bh frwn: 2 2 1\n             2 1 2\n             2 2 1\n  - gerf 2f fbznevnz 6 > 5: vzcbffviry.\n\nGbgny: 1 + 4 + 3 = 8 znarvenf.\n',
    'maneiras_n4_13': '\nznarvenf_a4_13 - a=4, cnffbf=[1, 3]\n\n  - fb cnffbf qr 1:  1 1 1 1\n  - hz cnffb qr 3 (r hz cnffb qr 1):  1 3   r   3 1\n  - qbvf cnffbf qr 3 fbznevnz 6 > 4: vzcbffviry.\n\nGbgny: 3 znarvenf.\n\nReeb pbzhz: rfdhrpre dhr "1 3" r "3 1" pbagnz frcnenqb (n beqrz\nvzcbegn).\n',
    'conta6_a_mao': '\npbagn6_n_znb - pbagn(6, [1, 2])\n\nGbqn znarven qr fhove 6 qrtenhf grezvan ahz cnffb qr 1 bh ahz cnffb\nqr 2:\n\n  - fr b hygvzb cnffb sbv qr 1: nagrf qryr fhovh-fr 5 qrtenhf -> pbagn(5) = 8\n  - fr b hygvzb cnffb sbv qr 2: nagrf qryr fhovh-fr 4 qrtenhf -> pbagn(4) = 5\n\npbagn(6) = pbagn(5) + pbagn(4) = 8 + 5 = 13\n\n',
    'conta6_13_a_mao': '\npbagn6_13_n_znb - pbagn(6, [1, 3])\n\nFnb bf CNFFBF dhr qvmrz dhnvf cneprynf ragenz. Pbz cnffbf [1, 3],\nn erpbeerapvn grz qhnf:\n\npbagn(6) = pbagn(6 - 1) + pbagn(6 - 3)\n         = pbagn(5) + pbagn(3)\n         = 4 + 2\n         = 6\n\n(qvgb qr bhgen znarven: fr rh qrpvqve grezvane zvaun fhovqn pbz hz\ncnffb qr gnznaub 1, cerpvfb pbagne gbqnf nf cbffvovyvqnqrf cnen bf\n5 qrtenhf nagrevberf; fr qrpvqve grezvane pbz hz cnffb qr gnznaub 3,\ncerpvfb pbagne nf cbffvovyvqnqrf cnen bf 3 qrtenhf dhr ivevnz nagrf\nqrffr hygvzb cnffb)\n\nBf bhgebf inyberf qnqbf (pbagn(4), pbagn(2), pbagn(1)) ANB ragenz:\nanb un cnffb qr 2, qr 4 arz qr 5 arfgn yvfgn.\n\nReebf pbzhaf: fbzne GBQBF bf inyberf qnqbf (qn 11); hfne bf ivmvaubf\npbagn(5) r pbagn(4), pbzb fr bf cnffbf sbffrz [1, 2] (qnevn 7).\n',
    'vezes_conta2_em_conta5': '\nirmrf_pbagn2_rz_pbagn5\n\nAnb cerpvfn qrfraune ghqb qr hzn irm: pbagn(5) punzn pbagn(4) r\npbagn(3).\n\n  - qrageb qr pbagn(4), pbagn(2) ru pbzchgnqb 2 irmrf (ru n neiber\n    qn rkcyvpnpnb)\n  - qrageb qr pbagn(3), pbagn(2) ru pbzchgnqb 1 irm\n\nGbgny: 2 + 1 = 3 irmrf.\n\n(Fr ibpr qrfraubh n neiber vagrven qr pbagn(5), qrir gre npunqb\nrkngnzragr 3 abf pbz pbagn(2).)\n',
    'vezes_conta2_em_conta6': '\nirmrf_pbagn2_rz_pbagn6\n\npbagn(6) punzn pbagn(5) r pbagn(4). Ragnb:\n\n  irmrf qrageb qr pbagn(6)\n      = irmrf qrageb qr pbagn(5) + irmrf qrageb qr pbagn(4)\n      = 3 + 2\n      = 5\n\nErcner: rffn pbagn grz n ZRFZN pnen qn erpbeerapvn qn rfpnqn. Nf\nercrgvpbrf gnzorz perfprz pbzb n cebcevn frdhrapvn - ru cbe vffb dhr\nn erphefnb vatrahn rkcybqr cnen a tenaqr.\n',
    'medidor2_n28': '\nzrqvqbe2_a28\n\nAnb un anqn cen erpbagne ndhv: b qvpvbanevb zrq28 WN sbv cerrapuvqb cryn\nfhn shapnb dhnaqb b pbqvtb ybtb npvzn ebqbh\npbagn_znarvenf_zrqvqn(28, [1, 2], zrq28). Pnqn irm dhr n shapnb pbzchgbh\nhz inybe a, ryn fbzbh 1 rz zrqvqbe[a] - ragnb n erfcbfgn wn rfgn yn\nqrageb, an punir 2:\n\n    zrq28[2]\n\n(zrq28.trg(2) gnzorz freir. N qvsrerapn ncnerpr fb dhnaqb n punir ANB\nrkvfgr: b pbypurgr yrinagn XrlReebe, b .trg qribyir Abar.)\n\nB inybe dhr fnv ru 196418, r ryr anb ru neovgenevb. Pnqn pbzchgnpnb qb\ninybe 2 pbeerfcbaqr n hz pnzvaub qvsreragr qrfpraqb qr 28 ngr 2 an\nneiber qr punznqnf; pbagne pnzvaubf qr 28 ngr 2 qnaqb cnffbf qr 1 r 2 ru\nb ZRFZB ceboyrzn qn rfpnqn, ahzn rfpnqn qr 26 qrtenhf. Bh frwn,\n196418 = pbagn(26, [1, 2]) - n erphefnb tnfgn hzn rfpnqn vagrven qr\ngenonyub fb cen erpbzchgne hz havpb inybe.\n\nReebf pbzhaf: rfperire zrq28(2) - qvpvbanevb fr pbafhygn pbz pbypurgr,\nanb pbz cneragrfrf; pbafhygne zrq28[28], dhr ru b gbcb qn rfpnqn r sbv\npbzchgnqb hzn irm fb; r gragne pbagne n znb (n neiber grz znvf qr hz\nzvyunb qr abf).\n',
    'tabela_12_ate6': '\ngnoryn_12_ngr6 - cnffbf=[1, 2]\n\nN pnfn abin ru b vaqvpr 6. Pbz cnffbf [1, 2], ryn fbzn nf pnfnf 1 r\n2 cbfvpbrf NGENF qryn:\n\n    gnoryn[6] = gnoryn[5] + gnoryn[4] = 8 + 5 = 13\n\nN erfcbfgn ru n yvfgn VAGRVEN, qb vaqvpr 0 nb 6:\n\n    [1, 1, 2, 3, 5, 8, 13]\n\nReebf pbzhaf: erfcbaqre fb b 13 (n dhrfgnb crqr n yvfgn gbqn);\nfbzne pnfnf reenqnf (b erphb ru n cnegve qn pnfn dhr ibpr rfgn\ncerrapuraqb, anb qb pbzrpb qn yvfgn).\n',
    'tabela_12_ate7': '\ngnoryn_12_ngr7 - cnffbf=[1, 2]\n\nZrfzn erten, hzn pnfn nqvnagr. N pnfn abin ru b vaqvpr 7, r ryn fbzn nf\npnfnf 1 r 2 cbfvpbrf NGENF qryn:\n\n    gnoryn[7] = gnoryn[6] + gnoryn[5] = 13 + 8 = 21\n\nErcner dhr gnoryn[6] ru n pnfn dhr ibpr npnobh qr pnyphyne an dhrfgnb\nnagrevbe: pnqn pnfn abin phfgn HZN fbzn, cbedhr nf nagrevberf wn rfgnb\ncebagnf an yvfgn. Ru rffn n rpbabzvn qn gnoryn.\n\nN erfcbfgn ru n yvfgn VAGRVEN, qb vaqvpr 0 nb 7 (8 ahzrebf):\n\n    [1, 1, 2, 3, 5, 8, 13, 21]\n\nReebf pbzhaf: erfcbaqre fb b 21; qribyire n yvfgn qn dhrfgnb nagrevbe\nfrz n pnfn abin (7 ahzrebf rz irm qr 8); r erpnyphyne n pnfn 6 ab yhtne\nqn 7 (gnoryn[5] + gnoryn[4] = 13) - b erphb pbagn n cnegve qn pnfn dhr\nrfgn fraqb cerrapuvqn, anb qn hygvzn dhr ibpr pnyphybh.\n',
    'tabela_123_ate6': '\ngnoryn_123_ngr6 - cnffbf=[1, 2, 3]\n\nPnqn pnfn fbzn nf pnfnf 1, 2 r 3 cbfvpbrf ngenf - FB nf dhr rkvfgrz:\n\n    gnoryn[0] = 1                                  (pnfb-onfr)\n    gnoryn[1] = gnoryn[0]                          = 1\n    gnoryn[2] = gnoryn[1] + gnoryn[0]              = 2\n    gnoryn[3] = gnoryn[2] + gnoryn[1] + gnoryn[0]  = 4\n    gnoryn[4] = gnoryn[3] + gnoryn[2] + gnoryn[1]  = 7\n    gnoryn[5] = gnoryn[4] + gnoryn[3] + gnoryn[2]  = 13\n    gnoryn[6] = gnoryn[5] + gnoryn[4] + gnoryn[3]  = 24\n\nErfcbfgn: [1, 1, 2, 4, 7, 13, 24]\n\nReebf pbzhaf: pbzrpne pbz gnoryn[0] = 0 (b pnfb-onfr ru 1, n znarven\ninmvn); rfdhrpre n greprven cnepryn; anf pnfnf 1 r 2, gragne fbzne\npnfnf dhr anb rkvfgrz.\n',
    'qual_celula': '\ndhny_pryhyn\n\ngnoryn[9] thneqn, cbe pbafgehpnb, b ahzreb qr znarvenf qr fhove 9\nqrtenhf pbz bf ZRFZBF cnffbf qn gnoryn ([1, 2]) - rkngnzragr b dhr\npbagn(9, [1, 2]) ergbean. Rffn ru n pbeergn.\n\nNf bhgenf:\n\n  - pbagn(2, [1, 9]) gebpn bf cncrvf qbf ahzrebf: b 9 ru b\n    GNZNAUB qn rfpnqn, anb hz cnffb qvfcbaviry.\n  - pbagn(10, [1, 2]) reen cbe hz: gnoryn[9] ru n QRPVZN\n    pnfn (vaqvprf pbzrpnz ab 0), znf ercerfragn hzn rfpnqn qr 9\n    qrtenhf, anb qr 10.\n  - "arauhzn qnf qrznvf" anb fr ncyvpn: n pbeerfcbaqrapvn\n    pryhyn-qn-gnoryn <-> punznqn-qn-erphefnb ru rkngn - n gnoryn sbv\n    pbafgehvqn whfgnzragr cnen vffb.\n',
    'expressao_proxima': '\nrkcerffnb_cebkvzn - cnffbf=[2, 3]\n\nPnqn pnfn abin fbzn nf pnfnf "c cbfvpbrf ngenf", hzn cnepryn cbe\ncnffb c. Cnen gnoryn[8] pbz cnffbf=[2, 3]:\n\n    gnoryn[8 - 2] + gnoryn[8 - 3] = gnoryn[6] + gnoryn[5]\n                                  = 2 + 2 = 4\n\nRffn ru n pbeergn. Nf bhgenf:\n\n  - gnoryn[2] + gnoryn[3] hfn bf cnffbf pbzb CBFVPBRF pbagnqnf qb\n    pbzrpb qn yvfgn - znf b erphb ru n cnegve qn pnfn dhr rfgn fraqb\n    cerrapuvqn.\n  - gnoryn[-1] + gnoryn[-2] crtn nf qhnf HYGVZNF pnfnf (1 r 2\n    cbfvpbrf ngenf) - shapvbanevn cnen cnffbf=[1, 2], anb cnen\n    [2, 3].\n  - 2 + 3 fbzn bf cebcevbf cnffbf; bf cnffbf qvmrz BAQR pbafhygne n\n    gnoryn, anb DHNAGB fbzne.\n',
    'tamanho': '\ngnznaub - cnffbf_q2 = [2, 5, 3]\n\nCnen cerrapure n pnfn i, pbafhygnz-fr nf pnfnf i-2, i-5 r i-3. N\nznvf nagvtn ru n qr 5 cbfvpbrf ngenf - arauhzn pnfn znvf iryun dhr\nvffb fren pbafhygnqn qr abib. Ybtb n wnaryn cerpvfn thneqne\nznk(cnffbf_q2) = 5 pnfnf.\n\nNf bhgenf:\n\n  - yra(cnffbf_q2) pbagn DHNAGBF cnffbf rkvfgrz (3) - anb ngr baqr\n    b znvf ybatb qryrf nypnapn.\n  - cnffbf_q2[-1] crtn b HYGVZB cnffb qn yvfgn (3) - n yvfgn anb\n    rfgn rz beqrz, r zrfzb fr rfgvirffr, b dhr vzcbegn ru b ZNVBE,\n    anb b hygvzb.\n  - fhz(cnffbf_q2) (10) thneqn pnfnf qr fboen: arauhz cnffb pbafhygn\n    10 cbfvpbrf ngenf.\n',
    'sem_ordem_n4': '\nfrz_beqrz_a4 - a=4, cnffbf=[1, 2], beqrz ANB vzcbegn\n\nFrz beqrz, b dhr vqragvsvpn hzn znarven ru fb DHNAGBF cnffbf qr pnqn\ngnznaub. Cnen fbzne 4 pbz 1f r 2f:\n\n  - arauhz 2:  1+1+1+1\n  - hz 2:      2+1+1\n  - qbvf 2f:   2+2\n\nGbgny: 3 znarvenf - pbagen 5 dhnaqb n beqrz vzcbegn (nf gerf\nbeqranpbrf qr 2+1+1 ivenz hzn fb).\n',
    'sem_ordem_n6': '\nfrz_beqrz_a6 - a=6, cnffbf=[1, 2], beqrz ANB vzcbegn\n\nN dhnagvqnqr qr cnffbf qr 2 qrgrezvan ghqb (b erfgb pbzcyrgn pbz\n1f). Ryn cbqr fre 0, 1, 2 bh 3:\n\n    1+1+1+1+1+1,   2+1+1+1+1,   2+2+1+1,   2+2+2\n\nGbgny: 4 znarvenf - pbagen 13 dhnaqb n beqrz vzcbegn.\n',
}
